name = "brandbone-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WORKER_VERSION = "2.0.0"
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BB_CACHE"
id = "baf0005a4d46461d8778322e83936d26"

[[kv_namespaces]]
binding = "BB_TASKS"
id = "a5b36b24090a4a42b704c452c56abb27"

[env.staging]
name = "brandbone-worker-staging"

[env.staging.vars]
WORKER_VERSION = "2.0.0-staging"
ENVIRONMENT = "staging"

[[env.staging.kv_namespaces]]
binding = "BB_CACHE"
id = "baf0005a4d46461d8778322e83936d26"

[[env.staging.kv_namespaces]]
binding = "BB_TASKS"
id = "a5b36b24090a4a42b704c452c56abb27"
